extern char *circlemud_version;
extern char *dirs[];
extern char *room_bits[];
extern char *exit_bits[];
extern char *sector_types[];
extern char *genders[];
extern char *position_types[];
extern char *player_bits[];
extern char *action_bits[];
extern char *preference_bits[];
extern char *affected_bits[];
extern char *connected_types[];
extern char *where[];
extern char *equipment_types[];
extern char *item_types[];
extern char *wear_bits[];
extern char *extra_bits[];
extern char *apply_types[];
extern char *container_bits[];
extern char *drinks[];
extern char *drinknames[];
extern char *color_liquid[];
extern char *fullness[];
extern char *weekdays[];
extern char *month_name[];
extern char *spell_wear_off_msg[];
extern char *npc_class_types[];
extern const char *loc[10];
extern const char *dist[9];
extern struct str_app_type str_app[];
extern char *weapon_types[];
extern const struct dex_skill_type dex_app_skill[];
extern const struct dex_skill_type race_app_skill[NUM_RACES];
extern const struct dex_app_type dex_app[];
extern const struct con_app_type con_app[];
extern const struct int_app_type int_app[];
extern const struct wis_app_type wis_app[];
extern int rev_dir[];
extern int movement_loss[];
extern const int drink_aff[][3];
